server:
  port: 2000

spring:
  profiles:
    active: prod
    
  datasource:
    url: jdbc:mysql://localhost:3306/DBS
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root